"""del unique=True param column 'file_name' in models.product

Revision ID: 0ab4d848a6e4
Revises: af1e3e312de7
Create Date: 2023-03-17 14:47:09.814223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab4d848a6e4'
down_revision = 'af1e3e312de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_file_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint('product_file_name_key', ['file_name'])

    # ### end Alembic commands ###
