"""added scientific name in products model

Revision ID: 675d42bd4a85
Revises: 0ab4d848a6e4
Create Date: 2023-04-19 21:01:06.062082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675d42bd4a85'
down_revision = '0ab4d848a6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scientific_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('scientific_name')

    # ### end Alembic commands ###
