"""del unique=True param column 'name' in models.product

Revision ID: af1e3e312de7
Revises: 56dd76f8f4ac
Create Date: 2023-03-17 14:35:50.488448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af1e3e312de7'
down_revision = '56dd76f8f4ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['file_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('product_name_key', ['name'])

    # ### end Alembic commands ###
